# Generated by Django 4.1.3 on 2022-12-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.IntegerField(max_length=11)),
                ('telefone', models.IntegerField(max_length=14)),
                ('senha', models.IntegerField(max_length=16)),
                ('bloco', models.IntegerField(max_length=3)),
                ('num_apartamento', models.IntegerField(max_length=3)),
            ],
        ),
    ]
