# Generated by Django 4.1.3 on 2022-12-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv_app', '0003_alter_morador_bloco_alter_morador_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='morador',
            name='senha',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='morador',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
    ]
