# Generated by Django 4.1.3 on 2022-12-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv_app', '0006_servico_visita_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
