# Generated by Django 4.1.3 on 2022-12-05 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgv_app', '0009_visita_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='qr_code',
        ),
    ]
