# Generated by Django 4.1.4 on 2022-12-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv_app', '0012_servicos_visitas_delete_servico_delete_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='Num_apartamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicos',
            name='bloco',
            field=models.IntegerField(default=0),
        ),
    ]
