# Generated by Django 4.1.4 on 2022-12-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgv_app', '0013_servicos_num_apartamento_servicos_bloco'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitas',
            name='Num_apartamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitas',
            name='bloco',
            field=models.IntegerField(default=0),
        ),
    ]
